### ISSUE TITLE
What does this project do differently compared to nestjs-console ?

### ISSUE THREAD

**Issue by elovin** [jmcdo29/nestjs-commander#10]
I ask this question here because there does not appear to be a forum or another communication channel for this project as far as I can tell. 

At the first glance both are based on the commander package and provide a nestjs like way to write cli applications.

So what does this project do differently compared to [nestjs-console](https://github.com/Pop-Code/nestjs-console) ?

**Comment by jmcdo29** [comment]
From a quick read through of the readme, I feel like this breaks up the commands and handlers better. I actually wasn't aware of `nestjs-console` when I made this, just of [nestjs-command](https://www.npmjs.com/package/nestjs-command).

The big win for this implementation, of course, in my opinion, is that it breaks out all of the option handlers to their own methods to allow for complex option handling logic, and has a well defined interface for all commands to make use of, giving more structure to the code. Where in `nestjs-console` you can have two or more commands in one class, with `nest-commander` there is a strict relationship of one class to one command, helping enforce encapsulation of the command and breaking things out.

It looks like `nestjs-console` has the ability to create commands during runtime, which is cool, but I'm not sure the use case on that.

**Comment by elovin** [comment]
> [...] with nest-commander there is a strict relationship of one class to one command, helping enforce encapsulation of the command and breaking things out

I like that mindset, thanks for your feedback.

**Comment by jmcdo29** [comment]
@seyfer NestJS-Console is also almost two years older than nest-commander, just as an FYI, so that could contribute to the star difference.

![image](https://github.com/jmcdo29/nest-commander/assets/28268680/42b0e1d6-c56e-4ffe-946a-249cc60c693b)
